### ISSUE TITLE
model-emit: `planMigration` assumes one journal — a composed vertical has six, and the choice between them is the execution order

### ISSUE THREAD

**Issue by markusahlstrand** [substrat-run/substrat#1207]
`planMigration(entities, journal)` takes **one** journal, and derives the next version from `journal.entries.length + 1`. `parseJournal` enforces the same thing hostilely — entry *i* must be numbered `pad(i + 1)`, or it throws.

That is right for a single-surface vertical. A vertical composed of surfaces does not have one journal, and the difference is not cosmetic: **which journal an entry goes into is the execution order.**

## What a multi-surface vertical actually looks like

CRM-EFF has six arrays, concatenated in `src/module.ts`:

```
core (14) → crm (28) → eka (5) → rutt (6) → teka (1) → styrelse (1)   = 55 entries
```

The kernel loops `for (const m of mod.migrations)` and never sorts by version, so that concatenation **is** the order they run in. Three consequences, each silent when wrong:

1. **The wrong array runs at the wrong time.** A declared `parents` emits a `REFERENCES`, and SQLite will happily create a child before its parent: the migration passes, and the first insert fails. Nothing in `planMigration` can know this, because it never sees the other five arrays.
2. **The count is not the number.** Ours has 55 entries but a highest prefix of `0054`, because `0010` appears twice (`0010-lead-edit` and `0010-rutt`, from when the surfaces numbered independently). `planMigration` would propose `0056`. The correct next version is `0055`, and a duplicate is a **boot failure** — the adapter throws `duplicate migration version`.
3. **A journal read as one contiguous counter cannot represent this at all.** We can pass a hand-built `Journal` to `planMigration`, but `parseJournal` would reject the same data.

## What we do about it

`tools/append-migration.mts` wraps `planMigration`: it requires `--surface <core|crm|eka|rutt|teka|styrelse>` and refuses to guess (that choice is the execution order, and a generator should not make it), numbers from **max prefix + 1** rather than the count, refuses a version that already exists, and passes through `planMigration`'s own refusals for what SQLite cannot do in place (a `NOT NULL` column with no default, a new `UNIQUE` on a populated table) — those still get written by hand, which is the point of the refusal.

It is ~200 lines and none of it is domain knowledge. Every composed vertical will write it.

## Ask

Teach the planner that a journal set is ordered:

```ts
planMigration(entities, journals: readonly { name: string; journal: Journal }[], opts: { surface: string })
```

or a thinner version of the same idea — accept the surface as an input, derive the version from the **maximum** observed prefix across all journals rather than a per-journal count, and relax `parseJournal` so a non-contiguous counter is data rather than a throw. The refusal for "new table, surface not stated" is worth having upstream too: it is the one that prevents a foreign key pointing forwards.

Evidence: `tools/append-migration.mts` and `tools/emit-migrations.mts` in Egeryds/CRM-EFF.

**Comment by markusahlstrand** [comment]
Picked this up in triage and stopped before code: the report checks out against `main`, but the ask forks in a way that changes what a shipped refusal means, so triage is not choosing for you.

Verified: `planMigration(entities, journal)` takes one journal (`packages/model-emit/src/plan.ts:61-63`) and numbers the next entry `pad(journal.entries.length + 1)` (`:228`); `parseJournal` throws unless entry *i* is `pad(i + 1)`, and its own message says why — "the counter is derived from position, so a gap or a duplicate means a bad merge, not a renumbering" (`:244-249`). So the contiguity check is not an oversight; it is a deliberate corruption detector, and the ask is to weaken it.

Three questions:

1. **Additive, or a new signature?** `planMigration` is exported from a published package. An additive `planMigration(entities, journal, opts?: { journals?, surface? })` keeps every existing caller compiling; the `readonly { name, journal }[]` shape in the ask does not. Which do you want — and if the array shape, does model-emit get a major bump, or do both overloads ship?

2. **What replaces the contiguity check once it is relaxed?** Position-derived numbering is currently what makes a bad merge loud. Reading the max prefix instead means `0010` twice across two surfaces is fine (your case), but `0010` twice in *one* surface is a boot failure the parser would no longer catch. Is the replacement rule "contiguous within a journal, unconstrained across journals", or "unique within a journal, nothing more"? The first keeps the detector for the single-surface case; the second cannot, because your own history has `0010-lead-edit` and `0010-rutt` from when the surfaces numbered independently — do those need to keep parsing as-is, or would you renumber?

3. **Does `planMigration` learn the concatenation order, or only its own place in it?** The FK-points-forward failure in your point 1 needs the planner to know that `core` runs before `crm`; naming a surface only tells it which array to write into. Is ordering in scope (an ordered journal set, with a refusal when a new table's `parents` resolve to a later surface), or is the ask limited to numbering — with ordering left to the vertical, as `tools/append-migration.mts` does today?

Whichever way this goes it also lands in the migration-diff checkpoint, so it wants a human on the diff regardless — the automation will not take it unattended.

— automated triage

**Comment by markusahlstrand** [comment]
Landed on `main` since the questions above — `8cc077a0` (*feat(model-emit): planMigration reads a journal set, not one journal (#1207)*, PR #1371) — and it took a fork on each of the three:

1. **Additive.** `planMigration(entities, journal, opts?: MigrationPlanOptions)` with `{ journals, surface }`; every existing caller still compiles and no major bump was needed (`packages/model-emit/src/plan.ts:107`).
2. **Contiguous within a journal, unconstrained across journals.** `parseJournal` takes `{ surface }`, and with it the detector relaxes from position-derived to *strictly increasing, never repeating* — so `0010` twice in one surface is still the bad merge it always was, while `0010` in two surfaces parses as the history it is (`:344-375`).
3. **Ordering is stated, never guessed.** The set IS the execution order: passing `journals` without `surface` is refused when anything would be CREATEd, a `surface` that is not a member of the set is refused, and a `journal` that is not one of `journals` is refused rather than slotted in (`:120-133`, `:305-320`).

So the ask looks delivered and this looks closable — leaving it open only for a human to confirm the fork choices read right.

— automated triage

**Comment by markusahlstrand** [comment]
Verified against `main` (`ebe283f1`): `8cc077a0` (#1371) delivers all four parts of the ask, and it is an ancestor of `main`.

- **The surface is an input** — `planMigration(entities, journal, opts?: MigrationPlanOptions)` with `{ journals, surface }` (`packages/model-emit/src/plan.ts:64-85`, `:107-110`). Additive, so every single-surface caller still compiles and passing nothing is the old behaviour unchanged.
- **The version comes from the maximum observed prefix, not a count** — `:334-338` reduces over every journal in the set and returns `pad(highest + 1)`. That is precisely the reported failure: a set whose entries outnumber its highest prefix (a counter repeated across surfaces that once numbered independently) no longer proposes a version that already exists and boots into `duplicate migration version`.
- **`parseJournal` is relaxed, and only where it should be** — `:370-391`. With a `surface`, a *skipping* counter is data; it still refuses a repeat or a step backwards, because that is a bad merge rather than a renumbering. With no surface the strict position rule is untouched.
- **The "new table, surface not stated" refusal is upstream** — `:305-313`, the one that stops a table being created before the parent it `REFERENCES`. Only a CREATE asks; an ALTER needs no such choice. A `surface` naming a journal outside the set is refused too (`:317-320`, via `Object.hasOwn` so a `toString` typo stays loud), as is appending to a journal that is not a member of `journals` (`:120-133`).

The planner does not check the *decision*, only that it was made — which is right, since the concatenation order belongs to the vertical, not the model.

The last comment left this open "for a human to confirm the fork choices read right". Each fork is documented in the code at the line cited above rather than only in the thread, so closing on that basis; reopen if any of the three reads wrong.

— automated triage
